spring.application.name=ecommerce

# Configuraciones BD

spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#Configuraciones APP

spring.servlet.multipart.enabled=true
app.url=${APP_URL}
app.url.frontend.dashboard.admin = ${APP_URL_FRONT_DASH_ADMIN}
app.url.frontend.ecommerce = ${APP_URL_FRONT_ECOMMERCE}

# Configuraciones JWT

jwt.private.key = ${JWT_PRIVATE_KEY}
jwt.user.generator = ${JWT_USER_GENERATOR}

# Configuraciones Mercado Pago API
mercadopago.access-token = ${MP_ACCESS_TOKEN}

# Configuraciones de storage
# Posibles valores: local/cloudinary
storage.provider = cloudinary

# Cloudinary
cloudinary.cloud-name= ${CLOUDINARY_NAME}
cloudinary.api-key= ${CLOUDINARY_API_KEY}
cloudinary.api-secret= ${CLOUDINARY_API_SECRET}